eSnacks/Controllers/OrdersController.cs
using System.Security.Claims;
using eSnacks.Data.Cart;
using eSnacks.Data.Services;
using eSnacks.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace eSnacks.Controllers
{
[Authorize] 
    public class OrdersController : Controller
    {
        private readonly IMenuItemService _menuItemsService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IMenuItemService menuItemsService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _menuItemsService = menuItemsService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _menuItemsService.GetMenuItemByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _menuItemsService.GetMenuItemByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            var price = _shoppingCart.GetShoppingCartTotal();
            
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, price, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

eSnacks/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using eSnacks.Data;
using eSnacks.Data.Services;
using eSnacks.Models;
using eSnacks.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace eSnacks.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class RestaurantController : Controller
    {
        private readonly IRestaurantService _service;

        public RestaurantController(IRestaurantService service)
        {
            _service = service;
        }

        // GET: Restaurant
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var restaurants = await _service.GetAllRestaurantsAsync();
            return restaurants != null ? View(restaurants) : Problem("Entity set 'ApplicationDbContext.City' is null.");
        }

        
        // GET: Restaurant/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var restaurantDetails = await _service.GetRestaurantByIdAsync(id);
            if (restaurantDetails == null) return NotFound();
            return View(restaurantDetails);
        }

        
        // GET: Restaurant/Create
        public async Task<IActionResult> Create()
        {
            var restaurantDropdownsData = await _service.GetRestaurantDropdownsValues();
            ViewBag.CityId = new SelectList(restaurantDropdownsData.Cities, "Id", "CityName");
            
            return View();
        }
        
        // POST: Restaurant/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RestaurantName,Address,PhotoUrl,Description,CityId")]RestaurantVM restaurant)
        {
            if (!ModelState.IsValid)
            {
                var restaurantDropdownsData = await _service.GetRestaurantDropdownsValues();
                ViewBag.CityId = new SelectList(restaurantDropdownsData.Cities, "Id", "CityName");
                
                return View(restaurant);
            }
            
            await _service.AddRestaurantAsync(restaurant);
            return RedirectToAction(nameof(Index));
        }
        

        // GET: Restaurant/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var restaurantDetails = await _service.GetRestaurantByIdAsync(id);
            if (restaurantDetails == null) return NotFound();
            
            var restaurantDropdownsData = await _service.GetRestaurantDropdownsValues();
            ViewBag.CityId = new SelectList(restaurantDropdownsData.Cities, "Id", "CityName");

            var restaurantDetailsVM = new RestaurantVM()
            {
                Id = restaurantDetails.Id,
                RestaurantName = restaurantDetails.RestaurantName,
                Address = restaurantDetails.Address,
                PhotoUrl = restaurantDetails.PhotoUrl,
                Description = restaurantDetails.Description,
                CityId = restaurantDetails.CityId,
            };
            
            return View(restaurantDetailsVM);
        }
        
        // POST: Restaurant/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RestaurantName,Address,PhotoUrl,Description,CityId")] RestaurantVM restaurant)
        {
            if (id != restaurant.Id) return NotFound();

            if (!ModelState.IsValid)
            {
                var restaurantDropdownsData = await _service.GetRestaurantDropdownsValues();
                ViewBag.CityId = new SelectList(restaurantDropdownsData.Cities, "Id", "CityName");
                
                return View(restaurant);
            }
            
            try
            {
                await _service.UpdateRestaurantAsync(restaurant);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (_service.GetRestaurantByIdAsync(id) == null)
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        
        // GET: Restaurant/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var restaurantDetails = await _service.GetRestaurantByIdAsync(id);
            if (restaurantDetails == null) return NotFound();
            return View(restaurantDetails);
        }

        // POST: Restaurant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var restaurantDetails = await _service.GetByIdAsync(id);
            if (restaurantDetails == null) return NotFound();

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
        
        [AllowAnonymous]
        public async Task<IActionResult> FindRestaurantsInCity(string cityName)
        {
            var restaurants = await _service.GetRestaurantsInCityAsync(cityName);
            
            if (!restaurants.Any())
            {
                TempData["NotFound"] = cityName;
                return RedirectToAction("Index", "Home");
            }
            
            TempData["CityName"] = cityName;
            return View("Index", restaurants);
        }
    }
}

eSnacks/Views/Orders/Index.cshtml
@model List<PlacedOrder>

@{ 
    ViewData["Title"] = "All orders";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <table class="table caption-top my-3">
            <caption class="display-6 my-3 text-center">List of all your orders</caption>
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Items</th>
                    <th>Total</th>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                    {
                        <th>User</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model)
                {
                <tr>
                    <td class="align-middle">@order.PlacedOrderId</td>
                    <td class="align-middle">
                        <ul style="list-style-type:none">
                            @foreach (var item in order.InOrders)
                            {
                                <li>
                                    <div class="alert alert-success" role="alert">
                                        <span class="badge text-bg-success">@item.Quantity</span> [@item.Price.ToString("c")] - @item.MenuItem.ItemName
                                    </div>
                                </li>
                            }
                        </ul>
                    </td>
                    <td class="align-middle">
                        @order.InOrders.Select(m => m.MenuItem.Price * m.Quantity).Sum().ToString("c")
                    </td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                    {
                        <td class="align-middle"> @order.User.FirstName @order.User.LastName </td>
                    }
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

eSnacks/Views/Orders/OrderCompleted.cshtml
<div class="row my-5">
    <div class="col-md-6 offset-3 alert alert-success text-center">
        <h2>Order completed successfully</h2>
        <p>You can check all your orders in the Orders section of your profile</p>
        <hr />
        <p>Thank you!</p>
    </div>
</div>

eSnacks/Views/Orders/ShoppingCart.cshtml
@using eSnacks.Models.ViewModels;
@model ShoppingCartVM

@{
    ViewData["Title"] = "Shopping cart summary";
}

<div class="row mt-5 mb-3">
    <div class="col-md-8 offset-2">
        <div class="text-center mb-5">
            <h2>You order summary</h2>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Selected amount</th>
                    <th>Menu Item</th>
                    <th>Restaurant</th>
                    <th>Price</th>
                    <th>Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ShoppingCart.ShoppingCartItems)
                {
                    <tr>
                        <td class="align-middle">@item.Quantity</td>
                        <td class="align-middle">@item.MenuItem.ItemName</td>
                        <td class="align-middle">@item.MenuItem.Restaurant.RestaurantName</td>
                        <td class="align-middle">@item.MenuItem.Price.ToString("c")</td>
                        <td class="align-middle">@((item.Quantity * item.MenuItem.Price).ToString("c"))</td>
                        <td class="align-middle">
                            <a class="text-danger mx-1" asp-controller="Orders" asp-action="RemoveItemFromShoppingCart" asp-route-id="@item.MenuItem.Id">
                                <i class="bi bi-dash-square text-decoration-none" style="font-size: 24px;"></i>
                            </a>
                            <a class="text-success mx-1" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.MenuItem.Id">
                                <i class="bi bi-plus-square" style="font-size: 24px;"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3"></td>
                    <td><b>Total:</b></td>
                    <td>
                        @Model.ShoppingCartTotal.ToString("c")
                    </td>
                    <td></td>
                </tr>
            </tfoot>
        </table>

        <div class="text-right my-5">
            <div class="btn-group">
                <a class="btn btn-outline-primary" asp-action="CompleteOrder">Complete order</a>
                <span style="padding:5px"></span>
                <a class="btn btn-outline-success" asp-controller="Restaurant" asp-action="Index">Add more items</a>
            </div>
        </div>
    </div>
</div>