eSnacks/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace eSnacks.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public class AccessDeniedModel : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

eSnacks/Areas/Identity/Pages/Account/ForgotPasswordConfirmation.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace eSnacks.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    [AllowAnonymous]
    public class ForgotPasswordConfirmation : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

eSnacks/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using eSnacks.Data.Services;
using eSnacks.Models;
using Microsoft.AspNetCore.Authorization;

namespace eSnacks.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _service;

        public CategoryController(ICategoryService service)
        {
            _service = service;
        }

        
        // GET: Category
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var categories = await _service.GetAllAsync();
            return categories != null ? View(categories) : Problem("Entity set 'ApplicationDbContext.City' is null.");
        }

        
        // GET: Category/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var categoryDetails = await _service.GetByIdAsync(id);
            if (categoryDetails == null) return NotFound();
            return View(categoryDetails);
        }

        
        // GET: Category/Create
        public IActionResult Create()
        {
            return View();
        }
        
        // POST: Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryName,Description")] Category category)
        {
            if (!ModelState.IsValid) return View(category);
            await _service.AddAsync(category);
            return RedirectToAction(nameof(Index));
        }
        

        // GET: Category/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var categoryDetails = await _service.GetByIdAsync(id);
            if (categoryDetails == null) return NotFound();
            return View(categoryDetails);
        }
        
        // POST: Category/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CategoryName,Description")] Category category)
        {
            if (id != category.Id) return NotFound();

            if (!ModelState.IsValid) return View(category);
            
            try
            {
                await _service.UpdateAsync(id, category);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (_service.GetByIdAsync(id) == null)
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        
        // GET: Category/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var categoryDetails = await _service.GetByIdAsync(id);
            if (categoryDetails == null) return NotFound();
            return View(categoryDetails);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categoryDetails = await _service.GetByIdAsync(id);
            if (categoryDetails == null) return NotFound();

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eSnacks/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using eSnacks.Data.Services;
using eSnacks.Models;
using Microsoft.AspNetCore.Authorization;

namespace eSnacks.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class CityController : Controller
    {
        private readonly ICityService _service;

        public CityController(ICityService service)
        {
            _service = service;
        }

        
        // GET: City
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var cities = await _service.GetAllAsync();
            return cities != null ? View(cities) : Problem("Entity set 'ApplicationDbContext.City' is null.");
        }

        
        // GET: City/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var cityDetails = await _service.GetByIdAsync(id);
            if (cityDetails == null) return NotFound();
            return View(cityDetails);
        }

        
        // GET: City/Create
        public IActionResult Create()
        {
            return View();
        }
        
        // POST: City/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CityName,ZipCode")]City city)
        {
            if (!ModelState.IsValid) return View(city);
            await _service.AddAsync(city);
            return RedirectToAction(nameof(Index));
        }
        

        // GET: City/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var cityDetails = await _service.GetByIdAsync(id);
            if (cityDetails == null) return NotFound();
            return View(cityDetails);
        }
        
        // POST: City/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CityName,ZipCode")] City city)
        {
            if (id != city.Id) return NotFound();
            
            if (!ModelState.IsValid) return View(city);
            
            try
            {
                await _service.UpdateAsync(id, city);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (_service.GetByIdAsync(id) == null)
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        
        // GET: City/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var cityDetails = await _service.GetByIdAsync(id);
            if (cityDetails == null) return NotFound();
            return View(cityDetails);
        }

        // POST: City/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return NotFound();

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eSnacks/Controllers/InOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using eSnacks.Data;
using eSnacks.Models;

namespace eSnacks.Controllers
{
    public class InOrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InOrderController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: InOrder
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.InOrders.Include(i => i.MenuItem).Include(i => i.PlacedOrder).ThenInclude(po => po.Restaurant);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: InOrder/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.InOrders == null)
            {
                return NotFound();
            }

            var inOrder = await _context.InOrders
                .Include(i => i.MenuItem)
                .Include(i => i.PlacedOrder)
                .ThenInclude(po => po.Restaurant)
                .FirstOrDefaultAsync(m => m.InOrderId == id);
            if (inOrder == null)
            {
                return NotFound();
            }

            return View(inOrder);
        }

        // GET: InOrder/Create
        public IActionResult Create()
        {
            ViewData["MenuItemId"] = new SelectList(_context.MenuItems, "Id", "ItemName");
            ViewData["PlacedOrderId"] = new SelectList(_context.PlacedOrders, "PlacedOrderId", "PlacedOrderId");
            return View();
        }

        // POST: InOrder/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InOrderId,Quantity,Price,Comment,PlacedOrderId,Id")] InOrder inOrder)
        {
            if (ModelState.IsValid)
            {
                _context.Add(inOrder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MenuItemId"] = new SelectList(_context.MenuItems, "Id", "ItemName", inOrder.MenuItemId);
            ViewData["PlacedOrderId"] = new SelectList(_context.PlacedOrders, "PlacedOrderId", "PlacedOrderId", inOrder.PlacedOrderId);
            return View(inOrder);
        }

        // GET: InOrder/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.InOrders == null)
            {
                return NotFound();
            }

            var inOrder = await _context.InOrders.FindAsync(id);
            if (inOrder == null)
            {
                return NotFound();
            }
            ViewData["MenuItemId"] = new SelectList(_context.MenuItems, "Id", "ItemName", inOrder.MenuItemId);
            ViewData["PlacedOrderId"] = new SelectList(_context.PlacedOrders, "PlacedOrderId", "PlacedOrderId", inOrder.PlacedOrderId);
            return View(inOrder);
        }

        // POST: InOrder/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InOrderId,Quantity,Price,Comment,PlacedOrderId,Id")] InOrder inOrder)
        {
            if (id != inOrder.InOrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(inOrder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InOrderExists(inOrder.InOrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MenuItemId"] = new SelectList(_context.MenuItems, "Id", "ItemName", inOrder.MenuItemId);
            ViewData["PlacedOrderId"] = new SelectList(_context.PlacedOrders, "PlacedOrderId", "PlacedOrderId", inOrder.PlacedOrderId);
            return View(inOrder);
        }

        // GET: InOrder/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.InOrders == null)
            {
                return NotFound();
            }

            var inOrder = await _context.InOrders
                .Include(i => i.MenuItem)
                .Include(i => i.PlacedOrder)
                .ThenInclude(po => po.Restaurant)
                .FirstOrDefaultAsync(m => m.InOrderId == id);
            if (inOrder == null)
            {
                return NotFound();
            }

            return View(inOrder);
        }

        // POST: InOrder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.InOrders == null)
            {
                return Problem("Entity set 'ApplicationDbContext.InOrders'  is null.");
            }
            var inOrder = await _context.InOrders.FindAsync(id);
            if (inOrder != null)
            {
                _context.InOrders.Remove(inOrder);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InOrderExists(int id)
        {
          return _context.InOrders.Any(e => e.InOrderId == id);
        }
    }
}

eSnacks/Controllers/OrdersController.cs
using System.Security.Claims;
using eSnacks.Data.Cart;
using eSnacks.Data.Services;
using eSnacks.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace eSnacks.Controllers
{
[Authorize] 
    public class OrdersController : Controller
    {
        private readonly IMenuItemService _menuItemsService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IMenuItemService menuItemsService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _menuItemsService = menuItemsService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _menuItemsService.GetMenuItemByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _menuItemsService.GetMenuItemByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            var price = _shoppingCart.GetShoppingCartTotal();
            
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, price, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

eSnacks/Views/Shared/_Identity.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<eSnacksUser> SignInManager
@inject UserManager<eSnacksUser> UserManager

<ul class="navbar-nav fw-medium justify-content-end position-relative d-flex">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item mx-1 px-3 nav-item-hover-li" style="padding-top: -15px;">
            <div class="dropdown d-flex flex-column align-items-center">
                <button class="dropdown-toggle nav-link text-dark border-0 bg-transparent" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-person-circle me-1" style="font-size: 26px;"></i>
                    <span>@UserManager.GetUserName(User)</span>
                </button>
                
                <ul class="dropdown-menu" aria-labelledby="profile-btn" style="left: unset !important">
                    <li>
                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">
                            
                            <i class="bi bi-info-circle"></i>
                            <span class="align-text-bottom">Profile</span>
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                            <i class="bi bi-list"></i>
                            <span>Orders</span> 
                        </a>
                    </li>

                    @if (User.IsInRole("Administrator"))
                    {
                        <li>
                            <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                                <i class="bi bi-people"></i> 
                                <span>Users</span> 
                            </a>
                        </li>
                    }
                </ul>
            </div>
            
        </li>
        <li class="nav-item mx-1 px-3 d-flex align-items-center nav-item-hover-li">
            <i class="bi bi-box-arrow-right d-inline-block" style="font-size: 26px;"></i>
            <form class="d-inline-block align-text-bottom" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new {area = ""})">
                <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item mx-1 px-3 nav-item-hover-li">
            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
        </li>
        <li class="nav-item mx-1 px-3 nav-item-hover-li">
            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
        </li>
    }
</ul>

eSnacks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="overflow-x-hidden" style="margin-right: calc(-1 * (100vw - 100%));">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - eSnacks</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/eSnacks.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/lib/bootstrap-select/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css">
</head>
<body style="padding-top: 0px;">
    @await RenderSectionAsync("Styles", required: false)

    <header>
        <nav class="navbar navbar-expand-xl navbar-light bg-body-tertiary border-bottom box-shadow ms-auto p-1">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-hexagon-fill me-2 text-danger" style="font-size:26px;"></i>
                    <span class="display-6">eSnacks</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav flex-grow-1 ms-auto fw-normal d-flex justify-content-center align-items-center" style="font-size: 20px; ">
                        <li class="nav-item nav-item-hover-li">
                            <a class="nav-link text-dark mx-2 active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item nav-item-hover-li">
                            <a class="nav-link text-dark mx-2" asp-area="" asp-controller="City" asp-action="Index">Cities</a>
                        </li>
                        <li class="nav-item nav-item-hover-li">
                            <a class="nav-link text-dark mx-2" asp-area="" asp-controller="Restaurant" asp-action="Index">Restaurants</a>
                        </li>
                        <li class="nav-item nav-item-hover-li">
                            <a class="nav-link text-dark mx-2" asp-area="" asp-controller="Category" asp-action="Index">Menu categories</a>
                        </li>
                        <li class="nav-item nav-item-hover-li">
                            <a class="nav-link text-dark mx-2" asp-area="" asp-controller="MenuItem" asp-action="Index">Menu Items</a>
                        </li>
                        @* <li class="nav-item nav-item-hover-li"> *@
                        @*     <a class="nav-link text-dark mx-2" asp-area="" asp-controller="InOrder" asp-action="Index">InOrder</a> *@
                        @* </li> *@
                        @* <li class="nav-item nav-item-hover-li"> *@
                        @*     <a class="nav-link text-dark mx-2" asp-area="" asp-controller="PlacedOrder" asp-action="Index">PlacedOrder</a> *@
                        @* </li> *@
                        @* <li class="nav-item nav-item-hover-li"> *@
                        @*     <a class="nav-link text-dark mx-2" asp-area="" asp-controller="OrderStatus" asp-action="Index">OrderStatus</a> *@
                        @* </li> *@
                    </ul>
                    
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                    
                    @* <partial name="_LoginPartial"/> *@
                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-3">
        <div class="container">
            @RenderBody()
        </div>
    </main>

    <footer class="border-top bg-dark text-center text-lg-start fixed-bottom">
        <div class="container p-3 text-center text-white-50">
            &copy; 2023 - eSnacks - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white-50">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap-select/dist/js/bootstrap-select.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>